#!/usr/bin/env bash
# create_integration_branch.sh — 統合ブランチ作成スクリプト（T2: 2026-04-19 制定）
#
# Usage:
#   bash scripts/create_integration_branch.sh <migration_name> [base_branch]
#
# Examples:
#   bash scripts/create_integration_branch.sh online-only-migration
#   bash scripts/create_integration_branch.sh calsail-phase2 origin/main
#
# 目的: main への直 merge を防ぐため、集合 migration を受ける統合ブランチを
# 正規手順で作成。feature branch → integration branch → 司令官 E2E → main の
# 4 段階フローを enforce する。

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

# 引数パース
MIGRATION_NAME="$1"
BASE_BRANCH="${2:-origin/main}"
DRY_RUN="${DRY_RUN:-0}"

if [ -z "$MIGRATION_NAME" ]; then
    cat <<USAGE >&2
Usage: create_integration_branch.sh <migration_name> [base_branch]
  migration_name: 統合対象を表す kebab-case 名（例: online-only-migration）
  base_branch:    分岐元。デフォルト origin/main

環境変数:
  DRY_RUN=1       実行せず計画のみ表示
USAGE
    exit 1
fi

# migration_name バリデーション（英小文字・数字・ハイフンのみ）
if [[ ! "$MIGRATION_NAME" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]]; then
    echo "[create_integration_branch] ERROR: migration_name は kebab-case (^[a-z0-9-]+$) で指定してください" >&2
    exit 1
fi

BRANCH_NAME="integration/${MIGRATION_NAME}"

# 既存ブランチチェック
if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
    echo "[create_integration_branch] ERROR: ブランチ '${BRANCH_NAME}' は既に存在します" >&2
    echo "  既存を使用: git checkout ${BRANCH_NAME}" >&2
    echo "  やり直し:   git branch -D ${BRANCH_NAME} （feature branch のマージ前のみ）" >&2
    exit 1
fi

# 作業ツリーが clean か確認
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "[create_integration_branch] ERROR: 作業ツリーに未コミットの変更があります" >&2
    echo "  git status で確認し、commit または stash してから再実行してください" >&2
    exit 1
fi

# fetch してから分岐（origin 参照時）
if [[ "$BASE_BRANCH" == origin/* ]]; then
    REMOTE_NAME="${BASE_BRANCH%%/*}"
    echo "[create_integration_branch] fetching ${REMOTE_NAME}..." >&2
    if [ "$DRY_RUN" = "0" ]; then
        git fetch "${REMOTE_NAME}" --quiet
    fi
fi

# base の存在確認
if ! git rev-parse --verify --quiet "$BASE_BRANCH" >/dev/null; then
    echo "[create_integration_branch] ERROR: base branch '${BASE_BRANCH}' が見つかりません" >&2
    exit 1
fi

BASE_SHA=$(git rev-parse "$BASE_BRANCH")
BASE_SHA_SHORT=${BASE_SHA:0:8}

echo "[create_integration_branch] plan:"
echo "  migration_name: ${MIGRATION_NAME}"
echo "  branch:         ${BRANCH_NAME}"
echo "  base:           ${BASE_BRANCH} (${BASE_SHA_SHORT})"
echo "  current HEAD:   $(git rev-parse --abbrev-ref HEAD) ($(git rev-parse --short HEAD))"

if [ "$DRY_RUN" = "1" ]; then
    echo "[create_integration_branch] DRY_RUN=1 — 実行をスキップ"
    exit 0
fi

# ブランチ作成 + チェックアウト
git checkout -b "$BRANCH_NAME" "$BASE_BRANCH"

# integration メタ情報を記録（後続レビューで参照）
META_DIR="$SCRIPT_DIR/coordination/integration"
mkdir -p "$META_DIR"
META_FILE="${META_DIR}/${MIGRATION_NAME}.yaml"

if [ ! -f "$META_FILE" ]; then
    cat > "$META_FILE" <<META
# Integration Branch Meta — ${MIGRATION_NAME}
# Auto-generated by scripts/create_integration_branch.sh
migration_name: ${MIGRATION_NAME}
branch: ${BRANCH_NAME}
base_branch: ${BASE_BRANCH}
base_sha: ${BASE_SHA}
created_at: $(date '+%Y-%m-%dT%H:%M:%S')
created_by: ${USER:-unknown}

# 集合 merge 予定の feature branch リスト（随時更新）
feature_branches: []

# 統合 E2E 状態
e2e_status: pending   # pending / passed / failed
e2e_approved_by: null # 司令官承認後に記録
merged_to_main_at: null
META
    echo "[create_integration_branch] meta created: coordination/integration/${MIGRATION_NAME}.yaml"
else
    echo "[create_integration_branch] WARN: meta file already exists, keeping existing: ${META_FILE}" >&2
fi

echo ""
echo "[create_integration_branch] SUCCESS"
echo "  checked out: ${BRANCH_NAME}"
echo "  next:        feature branch をこのブランチに merge、全部揃ったら司令官 E2E → main"
echo ""
echo "  ⚠️ main への直 push / 直 merge は禁止です（T2 プロトコル）"
